language: elixir
elixir:
  - 1.9
  - 1.10
  - 1.11
notifications:
  recipients:
    - bruce.williams@cargosense.com
    - devstopfix@gmail.com
otp_release:
  - 19.3
  - 20.3
  - 21.0
  - 22.0
  - 23.0
matrix:
  exclude:
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 23.0
    - elixir: 1.10
      otp_release: 19.3
    - elixir: 1.10
      otp_release: 20.3
    - elixir: 1.11
      otp_release: 19.3
    - elixir: 1.11
      otp_release: 20.3
