language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
notifications:
  recipients:
    - bruce.williams@cargosense.com
    - devstopfix@gmail.com
otp_release:
  - 19.3
  - 20.3
  - 21.0
  - 22.0
