language: elixir
elixir: 1.0.5
notifications:
  recipients:
    - bruce.williams@cargosense.com
otp_release:
  - 17.1
  - 17.5
  - 18.0
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test"
