name: CI

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: dev
    name: Lint
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
        elixir: ["1.13"]
        otp: ["24"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused

  test:
    runs-on: ${{ matrix.os }}
    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }}, OS ${{ matrix.os }}
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        elixir: ["1.14", "1.13", "1.12", "1.11"]
        otp: ["25", "24", "23", "22"]
        exclude:
          - elixir: "1.14"
            otp: "22"
          - elixir: "1.12"
            otp: "25"
          - elixir: "1.11"
            otp: "25"

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - run: mix deps.get --only test
      - run: mix deps.compile
      - run: mix compile
      - run: mix test
